### ISSUE TITLE
Quinta práctica

### ISSUE THREAD

**Issue by jinchuika** [Csanchezz/practica#5]
## Problema

Usando PHP, hacer un índice de contenido a partir del array de abajo.

``` php
$indice = array(
    array('titulo' => 'Introducción', 'pag' => '1'),
    array('titulo' => 'Objetivos', 'pag' => '2'),
    array('titulo' => 'Argumentación', 'pag' => '3'),
    array('titulo' => 'Solución al problema', 'pag' => '5'),
    array('titulo' => 'Justificación', 'pag' => '9'),
    array('titulo' => 'Validación', 'pag' => '10'),
    array('titulo' => 'Conclusión', 'pag' => '12')
    );
```

El índice debe ser una lista de elementos de HTML (< li >) que tenga vínculos hacia las páginas de cada sección.
## Restricciones
- [x] El array debe estar en un archivo separado que se llamará `config.php`.
- [x] Cada uno de los links a los que se envíe deben funcionar. Debe haber una carpeta llamada contenido/ que tendrá los archivos 1.php, 2.php, etc. donde el número en el nombre del archivo es el número de página.
- [x] La parte del algoritmo que crea el índice debe estar en un archivo separado que se llame `controlador.php`.
- [x] Se debe acceder al índice desde un archivo llamado `index.php`

**Comment by Csanchezz** [comment]
wtf! Chuik estas loco! :)
